services:
  # Serviço da Aplicação Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: danie
        uid: 1000
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      DB_USERNAME: root
      DB_PASSWORD: laravel
    networks:
      - laravel
    depends_on:
      db:
        condition: service_healthy

  # Serviço do PHP-FPM
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Serviço do Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app
      - php-fpm

  # Serviço do Banco de Dados MariaDB
  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-plaravel",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  laravel:
    driver: bridge
